--------------------------------------------------------------------------------
-- validate-select-catalog-role-coverage.sql
--
-- Validates what SELECT_CATALOG_ROLE really covers for this skill.
--
-- This script is intentionally split into two layers:
--   1. Session-based SQL checks
--   2. Stored PL/SQL checks that mimic packaged Native MCP functions
--
-- Expected outcome:
--   - session-based reads should pass
--   - stored definer-rights PL/SQL should NOT be safely covered by the role
--
-- Required DEFINE variables before calling:
--   test_user
--   test_password
--   connect_alias
--   wallet_zip
--------------------------------------------------------------------------------

WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

SET DEFINE ON
SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET SERVEROUTPUT ON
SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF

SET CLOUDCONFIG &&wallet_zip
CONNECT &&test_user/"&&test_password"@&&connect_alias
SET SERVEROUTPUT ON

PROMPT
PROMPT ===== CONNECTED USER =====
PROMPT

COLUMN current_user FORMAT A30
COLUMN current_schema FORMAT A30

SELECT
  USER AS session_user,
  SYS_CONTEXT('USERENV', 'CURRENT_USER') AS current_user,
  SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS current_schema
FROM dual;

PROMPT
PROMPT ===== SESSION-BASED SQL CHECKS UNDER SELECT_CATALOG_ROLE =====
PROMPT

DECLARE
  PROCEDURE run_count_check(p_name VARCHAR2, p_sql VARCHAR2) IS
    l_cnt NUMBER;
  BEGIN
    EXECUTE IMMEDIATE p_sql INTO l_cnt;
    DBMS_OUTPUT.PUT_LINE(RPAD(p_name, 42) || ' PASS rows=' || l_cnt);
  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(RPAD(p_name, 42) || ' FAIL ' || SQLERRM);
  END;
BEGIN
  run_count_check('V$SQL', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$SQL WHERE ROWNUM <= 5)');
  run_count_check('V$SQLSTATS', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$SQLSTATS WHERE ROWNUM <= 5)');
  run_count_check('V$SQLAREA_PLAN_HASH', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$SQLAREA_PLAN_HASH WHERE ROWNUM <= 5)');
  run_count_check('V$SQL_PLAN', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$SQL_PLAN WHERE ROWNUM <= 5)');
  run_count_check('V$SQL_PLAN_STATISTICS_ALL', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$SQL_PLAN_STATISTICS_ALL WHERE ROWNUM <= 5)');
  run_count_check('V$SQL_SHARED_CURSOR', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$SQL_SHARED_CURSOR WHERE ROWNUM <= 5)');
  run_count_check('V$SQLTEXT', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$SQLTEXT WHERE ROWNUM <= 5)');
  run_count_check('V$PARAMETER', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$PARAMETER WHERE ROWNUM <= 5)');
  run_count_check('V$SESSION', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$SESSION WHERE ROWNUM <= 5)');
  run_count_check('V$ACTIVE_SESSION_HISTORY', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$ACTIVE_SESSION_HISTORY WHERE ROWNUM <= 5)');
  run_count_check('V$SYSMETRIC_HISTORY', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$SYSMETRIC_HISTORY WHERE ROWNUM <= 5)');
  run_count_check('V$SYSTEM_EVENT', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$SYSTEM_EVENT WHERE ROWNUM <= 5)');
  run_count_check('V$SGASTAT', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$SGASTAT WHERE ROWNUM <= 5)');
  run_count_check('V$PGASTAT', 'SELECT COUNT(*) FROM (SELECT 1 FROM V$PGASTAT WHERE ROWNUM <= 5)');

  run_count_check('DBA_PROPERTY_GRAPHS', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_PROPERTY_GRAPHS WHERE ROWNUM <= 5)');
  run_count_check('DBA_PG_ELEMENTS', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_PG_ELEMENTS WHERE ROWNUM <= 5)');
  run_count_check('DBA_PG_EDGE_RELATIONSHIPS', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_PG_EDGE_RELATIONSHIPS WHERE ROWNUM <= 5)');
  run_count_check('DBA_TABLES', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_TABLES WHERE ROWNUM <= 5)');
  run_count_check('DBA_INDEXES', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_INDEXES WHERE ROWNUM <= 5)');
  run_count_check('DBA_IND_COLUMNS', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_IND_COLUMNS WHERE ROWNUM <= 5)');
  run_count_check('DBA_TAB_STATISTICS', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_TAB_STATISTICS WHERE ROWNUM <= 5)');
  run_count_check('DBA_TAB_COL_STATISTICS', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_TAB_COL_STATISTICS WHERE ROWNUM <= 5)');

  run_count_check('DBA_TABLESPACE_USAGE_METRICS', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_TABLESPACE_USAGE_METRICS WHERE ROWNUM <= 5)');
  run_count_check('DBA_TEMP_FREE_SPACE', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_TEMP_FREE_SPACE WHERE ROWNUM <= 5)');
  run_count_check('DBA_AUTO_INDEX_CONFIG', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_AUTO_INDEX_CONFIG WHERE ROWNUM <= 5)');
  run_count_check('DBA_AUTO_INDEX_IND_ACTIONS', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_AUTO_INDEX_IND_ACTIONS WHERE ROWNUM <= 5)');
  run_count_check('DBA_AUTO_INDEX_EXECUTIONS', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_AUTO_INDEX_EXECUTIONS WHERE ROWNUM <= 5)');
  run_count_check('DBA_HIST_SNAPSHOT', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_HIST_SNAPSHOT WHERE ROWNUM <= 5)');
  run_count_check('DBA_HIST_SYSMETRIC_SUMMARY', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_HIST_SYSMETRIC_SUMMARY WHERE ROWNUM <= 5)');
  run_count_check('DBA_HIST_SYSTEM_EVENT', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_HIST_SYSTEM_EVENT WHERE ROWNUM <= 5)');
  run_count_check('DBA_HIST_PGASTAT', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_HIST_PGASTAT WHERE ROWNUM <= 5)');
  run_count_check('DBA_HIST_ACTIVE_SESS_HISTORY', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_HIST_ACTIVE_SESS_HISTORY WHERE ROWNUM <= 5)');
  run_count_check('DBA_SQL_PLAN_BASELINES', 'SELECT COUNT(*) FROM (SELECT 1 FROM DBA_SQL_PLAN_BASELINES WHERE ROWNUM <= 5)');

  run_count_check(
    'DBMS_XPLAN.DISPLAY_CURSOR',
    q'[
      SELECT COUNT(*)
      FROM (
        SELECT *
        FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(
          (SELECT sql_id FROM V$SQL WHERE sql_id IS NOT NULL AND ROWNUM = 1),
          NULL,
          'BASIC'
        ))
        WHERE ROWNUM <= 5
      )
    ]'
  );
END;
/

PROMPT
PROMPT ===== STORED PL/SQL CHECKS UNDER ROLE-ONLY MODEL =====
PROMPT

PROMPT
PROMPT --- STATIC SQL FUNCTION AGAINST V$SQLSTATS ---
PROMPT

CREATE OR REPLACE FUNCTION ga_role_static_vsqlstats_fn
  RETURN NUMBER
AS
  l_cnt NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO l_cnt
  FROM V$SQLSTATS
  WHERE ROWNUM <= 5;

  RETURN l_cnt;
END;
/

SHOW ERRORS FUNCTION ga_role_static_vsqlstats_fn

PROMPT
PROMPT --- STATIC SQL FUNCTION AGAINST DBA_PROPERTY_GRAPHS ---
PROMPT

CREATE OR REPLACE FUNCTION ga_role_static_graph_fn
  RETURN NUMBER
AS
  l_cnt NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO l_cnt
  FROM DBA_PROPERTY_GRAPHS
  WHERE ROWNUM <= 5;

  RETURN l_cnt;
END;
/

SHOW ERRORS FUNCTION ga_role_static_graph_fn

PROMPT
PROMPT --- DYNAMIC SQL FUNCTION AGAINST V$SQLSTATS ---
PROMPT

CREATE OR REPLACE FUNCTION ga_role_dynamic_vsqlstats_fn
  RETURN NUMBER
AS
  l_cnt NUMBER;
BEGIN
  EXECUTE IMMEDIATE
    'SELECT COUNT(*) FROM V$SQLSTATS WHERE ROWNUM <= 5'
    INTO l_cnt;

  RETURN l_cnt;
END;
/

SHOW ERRORS FUNCTION ga_role_dynamic_vsqlstats_fn

PROMPT
PROMPT ===== OBJECT STATUS =====
PROMPT

COLUMN object_name FORMAT A35
COLUMN status FORMAT A12

SELECT object_name, status
FROM user_objects
WHERE object_name IN (
  'GA_ROLE_STATIC_VSQLSTATS_FN',
  'GA_ROLE_STATIC_GRAPH_FN',
  'GA_ROLE_DYNAMIC_VSQLSTATS_FN'
)
ORDER BY object_name;

PROMPT
PROMPT ===== COMPILATION ERRORS =====
PROMPT

COLUMN name FORMAT A35
COLUMN text FORMAT A120

SELECT name, line, position, text
FROM user_errors
WHERE name IN (
  'GA_ROLE_STATIC_VSQLSTATS_FN',
  'GA_ROLE_STATIC_GRAPH_FN',
  'GA_ROLE_DYNAMIC_VSQLSTATS_FN'
)
ORDER BY name, sequence;

PROMPT
PROMPT ===== DYNAMIC FUNCTION EXECUTION TEST =====
PROMPT

DECLARE
  l_cnt NUMBER;
BEGIN
  l_cnt := ga_role_dynamic_vsqlstats_fn;
  DBMS_OUTPUT.PUT_LINE('GA_ROLE_DYNAMIC_VSQLSTATS_FN           PASS value=' || l_cnt);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('GA_ROLE_DYNAMIC_VSQLSTATS_FN           FAIL ' || SQLERRM);
END;
/

EXIT
